[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["amagiddmxh <1107537248@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"